import os
import subprocess
import sys
from PIL import Image

def create_dummy_image(filename, size, color):
    img = Image.new('RGB', size, color=color)
    img.save(filename)

def test_nonsquare():
    # Setup directories
    if not os.path.exists('input'): os.makedirs('input')
    if not os.path.exists('output'): os.makedirs('output')

    print("Creating non-square content image (300x200)...")
    content_filename = 'test_nonsquare_content.jpg'
    content_path = os.path.join('input', content_filename)
    create_dummy_image(content_path, (300, 200), 'yellow')

    # Get path to main.py
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    main_script = os.path.join(project_root, 'main.py')

    print("Testing style transfer with non-square content and square style...")
    # Style 'anime' is likely square (generated by model) or we can use a dummy style
    # Let's use the 'anime' preset if available, or create a dummy one
    style_arg = 'anime'
    
    # Command: python main.py --content test_nonsquare_content.jpg --style anime --steps 10
    cmd = [
        sys.executable, main_script,
        '--content', content_filename,
        '--style', style_arg,
        '--steps', '10',
        '--imsize', '128'
    ]
    
    expected_output = os.path.join('output', 'test_nonsquare_content_anime.jpg')
    
    if os.path.exists(expected_output):
        os.remove(expected_output)

    try:
        subprocess.check_call(cmd)
        if os.path.exists(expected_output):
            print(f"SUCCESS: Output generated at {expected_output}")
            # Verify output size matches content aspect ratio (approximately, due to resizing)
            # imsize=128. Content is 300x200 (3:2). 
            # Resize(128) on 300x200 -> smaller edge 200 becomes 128. 
            # Scale factor = 128/200 = 0.64.
            # Width = 300 * 0.64 = 192.
            # So expected tensor shape is (1, 3, 128, 192) or (1, 3, 192, 128) depending on (H, W).
            # PIL size is (W, H). 300x200 is W=300, H=200.
            # Resize(128): H=200 -> 128. W=300 -> 192.
            # Output image should be 192x128.
            
            out_img = Image.open(expected_output)
            print(f"Output image size: {out_img.size}")
            if out_img.size == (192, 128):
                 print("SUCCESS: Output size is correct (192x128).")
            else:
                 print(f"WARNING: Output size {out_img.size} differs from expected (192, 128).")

        else:
            print(f"FAILURE: Output not found at {expected_output}")
    except subprocess.CalledProcessError as e:
        print(f"FAILURE: Process crashed with error {e}")
    finally:
        if os.path.exists(content_path): os.remove(content_path)
        if os.path.exists(expected_output): os.remove(expected_output)

if __name__ == '__main__':
    test_nonsquare()
